import sys


# Define Constant Type

class Const:
    class ConstError(TypeError):
        pass

    class ConstCaseError(ConstError):
        pass

    def __setattr__(self, key, value):
        if key in self.__dict__:
            raise self.ConstError("Can't change const value!")
        if not key.isupper():
            raise self.ConstCaseError('const "%s" is not all letters are capitalized' % key)
        self.__dict__[key] = value


sys.modules[__name__] = Const()

# Constants - Configuration
Const.HOST_NAME = "172.17.0.2"
Const.DB_NAME = "insurance"
Const.DB_USER = "manager"

# Constants - TABLE NAME - Enumeration
Const.TABLE_SRC_NAME_TYPE = "source_name_type"
Const.TABLE_MARK_COV_TYPE = "market_coverage_type"
Const.TABLE_PLAN_TYPE = "plan_type"
Const.TABLE_QHP_TYPE = "qhp_type"
Const.TABLE_CHILD_ONLY_TYPE = "child_only_offering_type"
Const.TABLE_M_METAL_TYPE = "medical_metal_level_type"
Const.TABLE_D_METAL_TYPE = "dental_metal_level_type"
Const.TABLE_TOBACCO_TYPE = "tobacco_type"
Const.TABLE_AGE_TYPE = "age_type"
Const.TABLE_FAMILY_TYPE = "family_type"
Const.TABLE_COPAY_TYPE = "copay_type"
Const.TABLE_COINS_TYPE = "coin_type"
Const.TABLE_LIMIT_UNIT_TYPE = "limit_unit_type"
Const.TABLE_DESIGN_TYPE = "design_type"

# Constants - TABLE NAME - Data Set
Const.TABLE_PLAN = "plans"
Const.TABLE_MEDICAL_PLAN = "medical_plans"
Const.TABLE_DENTAL_PLAN = "dental_plans"
Const.TABLE_M_PLAN_REFERRAL = "medical_plan_referral"
Const.TABLE_M_PLAN_SBC = "medical_plan_sbc"
Const.TABLE_M_PLAN_MOOP = "medical_plan_moop"
Const.TABLE_M_PLAN_MOOP_INT = "medical_plan_moop_integrated"
Const.TABLE_M_PLAN_DED = "medical_plan_ded"
Const.TABLE_M_PLAN_DED_INT = "medical_plan_ded_integrated"
Const.TABLE_D_PLAN_MOOP = "dental_plan_moop"
Const.TABLE_D_PLAN_DED = "dental_plan_ded"

# Constants - TABLE ATTRIBUTES - Plans
Const.PLAN_ID = "plan_id"
Const.PLAN_VAR_NAME = "plan_variant_name"
Const.STD_COMP_ID = "std_component_id"
Const.PLAN_MARK_NAME = "plan_marketing_name"
Const.PLAN_YEAR = "year"
Const.PLAN_STATE = "state"
Const.SOURCE_NAME = "source_name"
Const.IMPORT_DATE = "import_date"
Const.HIOS_PROD_ID = "hios_product_id"
Const.HPID = "hpid"
Const.NETWORK_ID = "network_id"
Const.SERV_AREA_ID = "service_area_id"
Const.FORMULARY_ID = "formulary_id"
Const.IS_NEW_PLAN = "is_new_plan"
Const.MARK_COVERAGE = "market_coverage"
Const.PLAN_TYPE = "plan_type"
Const.QHP_TYPE = "qhp_type"
Const.DESIGN_TYPE = "design_type"
Const.CHILD_ONLY = "child_only_offering"
Const.COMPOSITE_RATE = "composite_rate_offered"
Const.OUT_COUNTRY_COV = "out_of_country_coverage"
Const.OUT_COUNTRY_COV_DESC = "out_of_country_coverage_desc"
Const.OUT_SERV_AREA_COV = "out_of_service_area_coverage"
Const.OUT_SERV_AREA_COV_DESC = "out_of_service_area_coverage_desc"
Const.PLAN_EXCLUSIONS = "plan_level_exclusions"
Const.EST_ADV_PAYMENT_INDIAN = "est_advanced_payment_for_indian_plan"
Const.CSR_VAR_TYPE = "csr_variant_type"
Const.MULTI_NETWORK = "multiple_in_network_tiers"
Const.FIRST_TIER_UTIL = "first_tier_utilization"
Const.SECOND_TIER_UTIL = "second_tier_utilization"
Const.EFFECTIVE_DATE = "effective_date"
Const.EXPIRATION_DATE = "expiration_date"

# Constants - TABLE ATTRIBUTES - Medical Plans
Const.M_METAL_LEVEL = "metal_level"
Const.PREG_NOTICE = "is_notice_required_for_pregnancy"
Const.WELLNESS_OFFER = "is_wellness_program_offered"
Const.UNI_DESIGN = "unique_design"
Const.EHB_PERCENT = "ehb_percent_total_premium"

# Constants - TABLE ATTRIBUTES - Medical Plan Referral
Const.REFERRAL = "specialist_referral"

# Constants - TABLE ATTRIBUTES - Medical Plan SBC
Const.DED_BABY = "having_baby_deductible"
Const.COPAY_BABY = "having_baby_copayment"
Const.COINS_BABY = "having_baby_coinsurance"
Const.LIMIT_BABY = "having_baby_limit"
Const.DED_DIABETES = "having_diabetes_deductible"
Const.COPAY_DIABETES = "having_diabetes_copayment"
Const.COINS_DIABETES = "having_diabetes_coinsurance"
Const.LIMIT_DIABETES = "having_diabetes_limit"
Const.DED_FRACTURE = "having_simple_fracture_deductible"
Const.COPAY_FRACTURE = "having_simple_fracture_copayment"
Const.COINS_FRACTURE = "having_simple_fracture_coinsurance"
Const.LIMIT_FRACTURE = "having_simple_fracture_limit"

# Constants - TABLE ATTRIBUTES - Medical Plan MOOP/DED
Const.MEHB_INN_TIER1_INDIVIDUAL = "medical_inn_tier1_individual"
Const.MEHB_INN_TIER1_FAM_PERSON = "medical_inn_tier1_family_per_person"
Const.MEHB_INN_TIER1_FAM_GROUP = "medical_inn_tier1_family_per_group"
Const.MEHB_INN_TIER1_COINS = "medical_inn_tier1_coinsurance"  # only for deductible
Const.MEHB_INN_TIER2_INDIVIDUAL = "medical_inn_tier2_individual"
Const.MEHB_INN_TIER2_FAM_PERSON = "medical_inn_tier2_family_per_person"
Const.MEHB_INN_TIER2_FAM_GROUP = "medical_inn_tier2_family_per_group"
Const.MEHB_INN_TIER2_COINS = "medical_inn_tier2_coinsurance"  # only for deductible
Const.MEHB_OON_INDIVIDUAL = "medical_oon_individual"
Const.MEHB_OON_FAM_PERSON = "medical_oon_family_per_person"
Const.MEHB_OON_FAM_GROUP = "medical_oon_family_per_group"
Const.MEHB_COMB_INDIVIDUAL = "medical_comb_inn_oon_individual"
Const.MEHB_COMB_FAM_PERSON = "medical_comb_inn_oon_family_per_person"
Const.MEHB_COMB_FAM_GROUP = "medical_comb_inn_oon_family_per_group"
Const.DEHB_INN_TIER1_INDIVIDUAL = "drug_inn_tier1_individual"
Const.DEHB_INN_TIER1_FAM_PERSON = "drug_inn_tier1_family_per_person"
Const.DEHB_INN_TIER1_FAM_GROUP = "drug_inn_tier1_family_per_group"
Const.DEHB_INN_TIER1_COINS = "drug_inn_tier1_coinsurance"  # only for deductible
Const.DEHB_INN_TIER2_INDIVIDUAL = "drug_inn_tier2_individual"
Const.DEHB_INN_TIER2_FAM_PERSON = "drug_inn_tier2_family_per_person"
Const.DEHB_INN_TIER2_FAM_GROUP = "drug_inn_tier2_family_per_group"
Const.DEHB_INN_TIER2_COINS = "drug_inn_tier2_coinsurance"  # only for deductible
Const.DEHB_OON_INDIVIDUAL = "drug_oon_individual"
Const.DEHB_OON_FAM_PERSON = "drug_oon_family_per_person"
Const.DEHB_OON_FAM_GROUP = "drug_oon_family_per_group"
Const.DEHB_COMB_INDIVIDUAL = "drug_comb_inn_oon_individual"
Const.DEHB_COMB_FAM_PERSON = "drug_comb_inn_oon_family_per_person"
Const.DEHB_COMB_FAM_GROUP = "drug_comb_inn_oon_family_per_group"

# Constants - TABLE ATTRIBUTES - Medical Plan MOOP/DED Integrated
Const.TEHB_INN_TIER1_INDIVIDUAL = "total_inn_tier1_individual"
Const.TEHB_INN_TIER1_FAM_PERSON = "total_inn_tier1_family_per_person"
Const.TEHB_INN_TIER1_FAM_GROUP = "total_inn_tier1_family_per_group"
Const.TEHB_INN_TIER1_COINS = "total_inn_tier1_coinsurance"  # only for deductible
Const.TEHB_INN_TIER2_INDIVIDUAL = "total_inn_tier2_individual"
Const.TEHB_INN_TIER2_FAM_PERSON = "total_inn_tier2_family_per_person"
Const.TEHB_INN_TIER2_FAM_GROUP = "total_inn_tier2_family_per_group"
Const.TEHB_INN_TIER2_COINS = "total_inn_tier2_coinsurance"  # only for deductible
Const.TEHB_OON_INDIVIDUAL = "total_oon_individual"
Const.TEHB_OON_FAM_PERSON = "total_oon_family_per_person"
Const.TEHB_OON_FAM_GROUP = "total_oon_family_per_group"
Const.TEHB_COMB_INDIVIDUAL = "total_comb_inn_oon_individual"
Const.TEHB_COMB_FAM_PERSON = "total_comb_inn_oon_family_per_person"
Const.TEHB_COMB_FAM_GROUP = "total_comb_inn_oon_family_per_group"

# Constants - TABLE ATTRIBUTES - Dental Plans
Const.D_METAL_LEVEL = "metal_level"
Const.EHB_PEDIATRIC_QTY = "ehb_pediatric_dental_apportionment_qty"
Const.GUARANTEED_RATE = "is_guaranteed_rate"

# Constants - TABLE ATTRIBUTES - Dental Plan MOOP/DED
Const.INN_TIER1_INDIVIDUAL = "inn_tier1_individual"
Const.INN_TIER1_FAM_PERSON = "inn_tier1_family_per_person"
Const.INN_TIER1_FAM_GROUP = "inn_tier1_family_per_group"
Const.INN_TIER2_INDIVIDUAL = "inn_tier2_individual"
Const.INN_TIER2_FAM_PERSON = "inn_tier2_family_per_person"
Const.INN_TIER2_FAM_GROUP = "inn_tier2_family_per_group"
Const.OON_INDIVIDUAL = "oon_individual"
Const.OON_FAM_PERSON = "oon_family_per_person"
Const.OON_FAM_GROUP = "oon_family_per_group"
Const.COMB_INDIVIDUAL = "comb_inn_oon_individual"
Const.COMB_FAM_PERSON = "comb_inn_oon_family_per_person"
Const.COMB_FAM_GROUP = "comb_inn_oon_family_per_group"

# Constants - DATA SET - Plans
Const.CSV_PLAN_ID = "PlanId"
Const.CSV_PLAN_VAR_NAME = "PlanVariantMarketingName"
Const.CSV_PLAN_MARK_NAME = "PlanMarketingName"
Const.CSV_STD_COMP_ID = "StandardComponentId"
Const.CSV_PLAN_YEAR = "BusinessYear"
Const.CSV_PLAN_STATE = "StateCode"
Const.CSV_SOURCE_NAME = "SourceName"
Const.CSV_IMPORT_DATE = "ImportDate"
Const.CSV_HIOS_PROD_ID = "HIOSProductId"
Const.CSV_HPID = "HPID"
Const.CSV_NETWORK_ID = "NetworkId"
Const.CSV_SERV_AREA_ID = "ServiceAreaId"
Const.CSV_FORMULARY_ID = "FormularyId"
Const.CSV_IS_NEW_PLAN = "IsNewPlan"
Const.CSV_MARK_COVERAGE = "MarketCoverage"
Const.CSV_PLAN_TYPE = "PlanType"
Const.CSV_QHP_TYPE = "QHPNonQHPTypeId"
Const.CSV_DESIGN_TYPE = "DesignType"
Const.CSV_CHILD_ONLY = "ChildOnlyOffering"
Const.CSV_COMPOSITE_RATE = "CompositeRatingOffered"
Const.CSV_OUT_COUNTRY_COV = "OutOfCountryCoverage"
Const.CSV_OUT_COUNTRY_COV_DESC = "OutOfCountryCoverageDescription"
Const.CSV_OUT_SERV_AREA_COV = "OutOfServiceAreaCoverage"
Const.CSV_OUT_SERV_AREA_COV_DESC = "OutOfServiceAreaCoverageDescription"
Const.CSV_PLAN_EXCLUSIONS = "PlanLevelExclusions"
Const.CSV_EST_ADV_PAYMENT_INDIAN = "IndianPlanVariationEstimatedAdvancedPaymentAmountPerEnrollee"
Const.CSV_CSR_VAR_TYPE = "CSRVariationType"
Const.CSV_MULTI_NETWORK = "MultipleInNetworkTiers"
Const.CSV_FIRST_TIER_UTIL = "FirstTierUtilization"
Const.CSV_SECOND_TIER_UTIL = "SecondTierUtilization"
Const.CSV_EFFECTIVE_DATE = "PlanEffectiveDate"
Const.CSV_EXPIRATION_DATE = "PlanExpirationDate"
Const.CSV_METAL_LEVEL = "MetalLevel"
Const.CSV_PREG_NOTICE = "IsNoticeRequiredForPregnancy"
Const.CSV_WELLNESS_OFFER = "WellnessProgramOffered"
Const.CSV_UNI_DESIGN = "UniquePlanDesign"
Const.CSV_EHB_PERCENT = "EHBPercentTotalPremium"
Const.CSV_EHB_PEDIATRIC_QTY = "EHBPediatricDentalApportionmentQuantity"
Const.CSV_GUARANTEED_RATE = "IsGuaranteedRate"
Const.CSV_REFERRAL_REQUIRED = "IsReferralRequiredForSpecialist"
Const.CSV_REFERRAL = "SpecialistRequiringReferral"
Const.CSV_DENTAL_ONLY = "DentalOnlyPlan"
Const.CSV_DED_INTEGRATED = "MedicalDrugDeductiblesIntegrated"
Const.CSV_MOOP_INTEGRATED = "MedicalDrugMaximumOutofPocketIntegrated"

Const.CSV_DED_BABY = "SBCHavingaBabyDeductible"
Const.CSV_COPAY_BABY = "SBCHavingaBabyCopayment"
Const.CSV_COINS_BABY = "SBCHavingaBabyCoinsurance"
Const.CSV_LIMIT_BABY = "SBCHavingaBabyLimit"
Const.CSV_DED_DIABETES = "SBCHavingDiabetesDeductible"
Const.CSV_COPAY_DIABETES = "SBCHavingDiabetesCopayment"
Const.CSV_COINS_DIABETES = "SBCHavingDiabetesCoinsurance"
Const.CSV_LIMIT_DIABETES = "SBCHavingDiabetesLimit"
Const.CSV_DED_FRACTURE = "SBCHavingSimplefractureDeductible"
Const.CSV_COPAY_FRACTURE = "SBCHavingSimplefractureCopayment"
Const.CSV_COINS_FRACTURE = "SBCHavingSimplefractureCoinsurance"
Const.CSV_LIMIT_FRACTURE = "SBCHavingSimplefractureLimit"

Const.CSV_MEHB_INN_TIER1_INDIVIDUAL_MOOP = "MEHBInnTier1IndividualMOOP"
Const.CSV_MEHB_INN_TIER1_FAM_PERSON_MOOP = "MEHBInnTier1FamilyPerPersonMOOP"
Const.CSV_MEHB_INN_TIER1_FAM_GROUP_MOOP = "MEHBInnTier1FamilyPerGroupMOOP"
Const.CSV_MEHB_INN_TIER2_INDIVIDUAL_MOOP = "MEHBInnTier2IndividualMOOP"
Const.CSV_MEHB_INN_TIER2_FAM_PERSON_MOOP = "MEHBInnTier2FamilyPerPersonMOOP"
Const.CSV_MEHB_INN_TIER2_FAM_GROUP_MOOP = "MEHBInnTier2FamilyPerGroupMOOP"
Const.CSV_MEHB_OON_INDIVIDUAL_MOOP = "MEHBOutOfNetIndividualMOOP"
Const.CSV_MEHB_OON_FAM_PERSON_MOOP = "MEHBOutOfNetFamilyPerPersonMOOP"
Const.CSV_MEHB_OON_FAM_GROUP_MOOP = "MEHBOutOfNetFamilyPerGroupMOOP"
Const.CSV_MEHB_COMB_INDIVIDUAL_MOOP = "MEHBCombInnOonIndividualMOOP"
Const.CSV_MEHB_COMB_FAM_PERSON_MOOP = "MEHBCombInnOonFamilyPerPersonMOOP"
Const.CSV_MEHB_COMB_FAM_GROUP_MOOP = "MEHBCombInnOonFamilyPerGroupMOOP"
Const.CSV_DEHB_INN_TIER1_INDIVIDUAL_MOOP = "DEHBInnTier1IndividualMOOP"
Const.CSV_DEHB_INN_TIER1_FAM_PERSON_MOOP = "DEHBInnTier1FamilyPerPersonMOOP"
Const.CSV_DEHB_INN_TIER1_FAM_GROUP_MOOP = "DEHBInnTier1FamilyPerGroupMOOP"
Const.CSV_DEHB_INN_TIER2_INDIVIDUAL_MOOP = "DEHBInnTier2IndividualMOOP"
Const.CSV_DEHB_INN_TIER2_FAM_PERSON_MOOP = "DEHBInnTier2FamilyPerPersonMOOP"
Const.CSV_DEHB_INN_TIER2_FAM_GROUP_MOOP = "DEHBInnTier2FamilyPerGroupMOOP"
Const.CSV_DEHB_OON_INDIVIDUAL_MOOP = "DEHBOutOfNetIndividualMOOP"
Const.CSV_DEHB_OON_FAM_PERSON_MOOP = "DEHBOutOfNetFamilyPerPersonMOOP"
Const.CSV_DEHB_OON_FAM_GROUP_MOOP = "DEHBOutOfNetFamilyPerGroupMOOP"
Const.CSV_DEHB_COMB_INDIVIDUAL_MOOP = "DEHBCombInnOonIndividualMOOP"
Const.CSV_DEHB_COMB_FAM_PERSON_MOOP = "DEHBCombInnOonFamilyPerPersonMOOP"
Const.CSV_DEHB_COMB_FAM_GROUP_MOOP = "DEHBCombInnOonFamilyPerGroupMOOP"
Const.CSV_TEHB_INN_TIER1_INDIVIDUAL_MOOP = "TEHBInnTier1IndividualMOOP"
Const.CSV_TEHB_INN_TIER1_FAM_PERSON_MOOP = "TEHBInnTier1FamilyPerPersonMOOP"
Const.CSV_TEHB_INN_TIER1_FAM_GROUP_MOOP = "TEHBInnTier1FamilyPerGroupMOOP"
Const.CSV_TEHB_INN_TIER2_INDIVIDUAL_MOOP = "TEHBInnTier2IndividualMOOP"
Const.CSV_TEHB_INN_TIER2_FAM_PERSON_MOOP = "TEHBInnTier2FamilyPerPersonMOOP"
Const.CSV_TEHB_INN_TIER2_FAM_GROUP_MOOP = "TEHBInnTier2FamilyPerGroupMOOP"
Const.CSV_TEHB_OON_INDIVIDUAL_MOOP = "TEHBOutOfNetIndividualMOOP"
Const.CSV_TEHB_OON_FAM_PERSON_MOOP = "TEHBOutOfNetFamilyPerPersonMOOP"
Const.CSV_TEHB_OON_FAM_GROUP_MOOP = "TEHBOutOfNetFamilyPerGroupMOOP"
Const.CSV_TEHB_COMB_INDIVIDUAL_MOOP = "TEHBCombInnOonIndividualMOOP"
Const.CSV_TEHB_COMB_FAM_PERSON_MOOP = "TEHBCombInnOonFamilyPerPersonMOOP"
Const.CSV_TEHB_COMB_FAM_GROUP_MOOP = "TEHBCombInnOonFamilyPerGroupMOOP"

Const.CSV_MEHB_INN_TIER1_INDIVIDUAL_DED = "MEHBDedInnTier1Individual"
Const.CSV_MEHB_INN_TIER1_FAM_PERSON_DED = "MEHBDedInnTier1FamilyPerPerson"
Const.CSV_MEHB_INN_TIER1_FAM_GROUP_DED = "MEHBDedInnTier1FamilyPerGroup"
Const.CSV_MEHB_INN_TIER1_COINS_DED = "MEHBDedInnTier1Coinsurance"
Const.CSV_MEHB_INN_TIER2_INDIVIDUAL_DED = "MEHBDedInnTier2Individual"
Const.CSV_MEHB_INN_TIER2_FAM_PERSON_DED = "MEHBDedInnTier2FamilyPerPerson"
Const.CSV_MEHB_INN_TIER2_FAM_GROUP_DED = "MEHBDedInnTier2FamilyPerGroup"
Const.CSV_MEHB_INN_TIER2_COINS_DED = "MEHBDedInnTier2Coinsurance"
Const.CSV_MEHB_OON_INDIVIDUAL_DED = "MEHBDedOutOfNetIndividual"
Const.CSV_MEHB_OON_FAM_PERSON_DED = "MEHBDedOutOfNetFamilyPerPerson"
Const.CSV_MEHB_OON_FAM_GROUP_DED = "MEHBDedOutOfNetFamilyPerGroup"
Const.CSV_MEHB_COMB_INDIVIDUAL_DED = "MEHBDedCombInnOonIndividual"
Const.CSV_MEHB_COMB_FAM_PERSON_DED = "MEHBDedCombInnOonFamilyPerPerson"
Const.CSV_MEHB_COMB_FAM_GROUP_DED = "MEHBDedCombInnOonFamilyPerGroup"
Const.CSV_DEHB_INN_TIER1_INDIVIDUAL_DED = "DEHBDedInnTier1Individual"
Const.CSV_DEHB_INN_TIER1_FAM_PERSON_DED = "DEHBDedInnTier1FamilyPerPerson"
Const.CSV_DEHB_INN_TIER1_FAM_GROUP_DED = "DEHBDedInnTier1FamilyPerGroup"
Const.CSV_DEHB_INN_TIER1_COINS_DED = "DEHBDedInnTier1Coinsurance"
Const.CSV_DEHB_INN_TIER2_INDIVIDUAL_DED = "DEHBDedInnTier2Individual"
Const.CSV_DEHB_INN_TIER2_FAM_PERSON_DED = "DEHBDedInnTier2FamilyPerPerson"
Const.CSV_DEHB_INN_TIER2_FAM_GROUP_DED = "DEHBDedInnTier2FamilyPerGroup"
Const.CSV_DEHB_INN_TIER2_COINS_DED = "DEHBDedInnTier2Coinsurance"
Const.CSV_DEHB_OON_INDIVIDUAL_DED = "DEHBDedOutOfNetIndividual"
Const.CSV_DEHB_OON_FAM_PERSON_DED = "DEHBDedOutOfNetFamilyPerPerson"
Const.CSV_DEHB_OON_FAM_GROUP_DED = "DEHBDedOutOfNetFamilyPerGroup"
Const.CSV_DEHB_COMB_INDIVIDUAL_DED = "DEHBDedCombInnOonIndividual"
Const.CSV_DEHB_COMB_FAM_PERSON_DED = "DEHBDedCombInnOonFamilyPerPerson"
Const.CSV_DEHB_COMB_FAM_GROUP_DED = "DEHBDedCombInnOonFamilyPerGroup"
Const.CSV_TEHB_INN_TIER1_INDIVIDUAL_DED = "TEHBDedInnTier1Individual"
Const.CSV_TEHB_INN_TIER1_FAM_PERSON_DED = "TEHBDedInnTier1FamilyPerPerson"
Const.CSV_TEHB_INN_TIER1_FAM_GROUP_DED = "TEHBDedInnTier1FamilyPerGroup"
Const.CSV_TEHB_INN_TIER1_COINS_DED = "TEHBDedInnTier1Coinsurance"
Const.CSV_TEHB_INN_TIER2_INDIVIDUAL_DED = "TEHBDedInnTier2Individual"
Const.CSV_TEHB_INN_TIER2_FAM_PERSON_DED = "TEHBDedInnTier2FamilyPerPerson"
Const.CSV_TEHB_INN_TIER2_FAM_GROUP_DED = "TEHBDedInnTier2FamilyPerGroup"
Const.CSV_TEHB_INN_TIER2_COINS_DED = "TEHBDedInnTier2Coinsurance"
Const.CSV_TEHB_OON_INDIVIDUAL_DED = "TEHBDedOutOfNetIndividual"
Const.CSV_TEHB_OON_FAM_PERSON_DED = "TEHBDedOutOfNetFamilyPerPerson"
Const.CSV_TEHB_OON_FAM_GROUP_DED = "TEHBDedOutOfNetFamilyPerGroup"
Const.CSV_TEHB_COMB_INDIVIDUAL_DED = "TEHBDedCombInnOonIndividual"
Const.CSV_TEHB_COMB_FAM_PERSON_DED = "TEHBDedCombInnOonFamilyPerPerson"
Const.CSV_TEHB_COMB_FAM_GROUP_DED = "TEHBDedCombInnOonFamilyPerGroup"
